services:
  app:
    image: 'homework_image'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
    ports:
      - "8081:8080"

  db:
    image: postgres
    container_name: homework_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgres
    volumes:
      - homework_volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: homework1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: admin123
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/homework1
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: 12345
    ports:
      - 8080:8080
      - 8443:8443
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak_network

volumes:
  homework_volume:
  postgres_data:

networks:
  keycloak_network:
    driver: bridge